export const questions = [
  {
    question: "01 - Gosto de fazer coisas que outras pessoas consideram fora do comum.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "02 - Gostaria de realizar um grande feito ou grande obra na minha vida.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "03 - Gosto de experimentar novidades e mudanças em meu dia-a-dia.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "04 - Não gosto de situações em que se exige que eu me comporte de determinada maneira.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "05 - Gosto de dizer o que eu penso a respeito das coisas.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question:
      "06 - Gosto de saber o que grandes personalidades disseram sobre os problemas pelos quais eu me interesso.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "07 - Gosto de ser capaz de fazer as coisas melhor do que as outras pessoas.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "08 - Gosto de concluir qualquer trabalho ou tarefa que tenha começado.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "09 - Gosto de ajudar meus amigos quando eles estão com problemas.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "10 - Não costumo abandonar um quebra-cabeça ou problema antes que consiga resolvê-lo.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "11 - Gosto de dizer aos outros como fazer seus trabalhos.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question:
      "12 - Gostaria de ser considerado(a) uma autoridade em algum trabalho, profissão ou campo de especialização.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "13 - Gosto de experimentar e provar coisas novas.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question:
      "14 - Quando tenho alguma tarefa para fazer, gosto de começar logo e permanecer trabalhando até completá-la.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "15 - Aceito com prazer a liderança das pessoas que admiro.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "16 - Gosto de trabalhar horas a fio sem ser interrompido(a).",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "17 - Gosto que meus amigos me dêem muita atenção quando estou sofrendo ou doente.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "18 - Costumo analisar minhas intenções e sentimentos.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "19 - Gosto de fazer com carinho pequenos favores a meus amigos.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "20 - Gosto de ficar acordado(a) até tarde para terminar um trabalho.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "21 - Gosto de andar pelo país e ver lugares diferentes.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "22 - Gosto de analisar os sentimentos e intenções dos outros.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "23 - Gosto de fazer gozação com pessoas que fazem coisas que eu considero estúpidas.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "24 - Tenho vontade de me vingar quando alguém me insulta.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "25 - Gosto de pensar sobre o caráter dos meus amigos e tentar descobrir o que os faz serem como são.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "26 - Sou leal aos meus amigos.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "27 - Gosto de levar um trabalho ou tarefa até o fim antes de começar outro.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "28 - Gosto de dizer aos meus superiores que eles fizeram um bom trabalho, quando acredito nisso.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "29 - Gosto que meus amigos sejam solidários comigo e me animem quando estou deprimido(a).",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "30 - Antes de começar um trabalho, gosto de organizá-lo e planejá-lo.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "31 - Gosto que meus amigos demonstrem muito afeto por mim.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "32 - Gosto de realizar tarefas que, na opinião dos outros, exigem habilidade e esforço.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "33 - Gosto de ser bem-sucedido nas coisas que faço.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "34 - Gosto de fazer amizades.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "35 - Gosto de ser considerado(a) um(a) líder pelos outros.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "36 - Gosto de realizar com afinco (sem descanso) qualquer trabalho que faço.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "37 - Gosto de participar de grupos cujos membros se tratem com afeto e amizade.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "38 - Sinto-me satisfeito(a) quando realizo bem um trabalho difícil.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "39 - Tenho vontade de mandar os outros calarem a boca quando discordo deles.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "40 - Gosto de fazer coisas do meu jeito sem me importar com o que os outros possam pensar.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "41 - Gosto de viajar e conhecer o país.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "42 - Gosto de me fixar em um trabalho ou problema mesmo quando a solução pareça extremamente difícil.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "43 - Gosto de conhecer novas pessoas.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "44 - Gosto de dividir coisas com os outros.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "45 - Sinto-me satisfeito(a) quando consigo convencer e influenciar os outros.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "46 - Gosto de demonstrar muita afeição por meus amigos.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "47 - Gosto de prestar favores aos outros.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "48 - Gosto de seguir instruções e fazer o que é esperado de mim.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "49 - Gosto de elogiar alguém que admiro.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
  {
    question: "50 - Quando planejo alguma coisa, procuro sugestões de pessoas que respeito.",
    options: [
      { value: "1", label: "1 = Nada característico" },
      { value: "2", label: "2 = Muito pouco característico" },
      { value: "3", label: "3 = Pouco característico" },
      { value: "4", label: "4 = Indiferente" },
      { value: "5", label: "5 = Característico" },
      { value: "6", label: "6 = Muito característico" },
      { value: "7", label: "7 = Totalmente característico" },
    ],
  },
]
